services:
    domain.container:
        class: DomainBundle\Container
        arguments:
            - '@service_container'

    #repositories
    domain.repository.team:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Domain\Entity\Team
    domain.repository.player:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Domain\Entity\Player
    domain.repository.season:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Domain\Entity\Season
    domain.repository.league:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Domain\Entity\League
    domain.repository.seasonteam:
            class: Doctrine\ORM\EntityRepository
            factory: ['@doctrine.orm.default_entity_manager', getRepository]
            arguments:
                - Domain\Entity\SeasonTeam

    #usecases
    domain.use_case.create_season_use_case:
       class: Domain\UseCase\CreateSeasonUseCase
       arguments: ['@domain.container']

    domain.use_case.create_team_use_case:
        class: Domain\UseCase\CreateTeamUseCase
        arguments: ['@domain.container']

    domain.use_case.create_season_team_use_case:
        class: Domain\UseCase\CreateSeasonTeamUseCase
        arguments: ['@domain.container']