services:
    domain.container:
        class: DomainBundle\Container
        arguments:
            - '@service_container'

    #repositories
    domain.repository.team:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Domain\Entity\Team
    domain.repository.player:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Domain\Entity\Player
    domain.repository.season:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Domain\Entity\Season
    domain.repository.league:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Domain\Entity\League

    #usecases
    domain.usecase.create_season_use_case:
       class: Domain\UseCase\CreateSeasonUseCase
       arguments: ['@domain.container']