Domain\Entity\Game:
    type: entity
    repositoryClass: DomainBundle\Repository\GameRepository
    id:
        id:
            type: integer
            generator: { strategy: NONE }
    fields:
        place:
            type: string
        datetime:
            type: datetime
        type:
            type: gametype
        state:
            type: integer
        membersA:
            type: array
            nullable: true
        membersB:
            type: array
            nullable: true
    manyToOne:
        season:
            targetEntity: Domain\Entity\Season
            joinColumn:
                name: season_id
                referencedColumnName: id
        seasonTeamA:
            targetEntity: Domain\Entity\SeasonTeam
            joinColumn:
                name: seasonteam_a_id
                referencedColumnName: id
        seasonTeamB:
            targetEntity: Domain\Entity\SeasonTeam
            joinColumn:
                name: seasonteam_b_id
                referencedColumnName: id