Domain\Entity\GoalEvent:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: NONE }
    fields:
        secondsFromStart:
            type: integer
        period:
            type: integer

    manyToOne:
        game:
            targetEntity: Domain\Entity\Game
            joinColumn:
                name: game_id
                referencedColumnName: id
        member:
            targetEntity: Domain\Entity\SeasonTeamMember
            joinColumn:
                name: member_id
                referencedColumnName: id
        assistantA:
            targetEntity: Domain\Entity\SeasonTeamMember
            joinColumn:
                name: assistant_a_id
                referencedColumnName: id
        assistantB:
            targetEntity: Domain\Entity\SeasonTeamMember
            joinColumn:
                name: assistant_b_id
                referencedColumnName: id