Domain\Entity\GoalkeeperEvent:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: NONE }
    fields:
        duration:
            type: integer
        goals:
            type: integer
        bullets:
            type: integer

    manyToOne:
        game:
            targetEntity: Domain\Entity\Game
            joinColumn:
                name: game_id
                referencedColumnName: id
        member:
            targetEntity: Domain\Entity\SeasonTeamMember
            joinColumn:
                name: member_id
                referencedColumnName: id