Domain\Entity\League:
    type: entity
    repositoryClass: DomainBundle\Repository\LeagueRepository
    id:
        id:
            type: integer
            generator: { strategy: NONE }
    oneToOne:
        metadata:
            targetEntity: DomainBundle\Entity\LeagueMetadata
            cascade: ["persist"]
            joinColumn:
                name: metadata_id
                referencedColumnName: id