Domain\Entity\PenaltyEvent:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: NONE }
    fields:
        secondsFromStart:
            type: integer
        penaltyTimeType:
            type: string

    manyToOne:
        game:
            targetEntity: Domain\Entity\Game
            joinColumn:
                name: game_id
                referencedColumnName: id
        member:
            targetEntity: Domain\Entity\SeasonTeamMember
            joinColumn:
                name: member_id
                referencedColumnName: id