Domain\Entity\Player:
    type: entity
    repositoryClass: DomainBundle\Repository\PlayerRepository
    id:
        id:
            type: integer
            generator: { strategy: NONE }
    oneToOne:
        metadata:
            targetEntity: DomainBundle\Entity\PlayerMetadata
            cascade: ["persist"]
            joinColumn:
                name: metadata_id
                referencedColumnName: id