Domain\Entity\SeasonTeamMember:
    type: entity
    repositoryClass: DomainBundle\Repository\SeasonTeamMemberRepository
    id:
        id:
            type: integer
            generator: { strategy: NONE }
    fields:
        type:
            type: string

    manyToOne:
        seasonTeam:
            targetEntity: Domain\Entity\SeasonTeam
            joinColumn:
                name: season_team_id
                referencedColumnName: id
        player:
            targetEntity: Domain\Entity\Player
            joinColumn:
                name: player_id
                referencedColumnName: id