app:
    resource: '@AppBundle/Controller/'
    type: annotation

control:
    resource: '@ControlBundle/Controller/'
    type: annotation
    prefix: /control

fos_user_security_logout:
    path:     /logout
    defaults: { _controller: FOSUserBundle:Security:logout }

fos_user_resetting_request:
    path:     /restore
    defaults: { _controller: FOSUserBundle:Resetting:request }

fos_user_resetting_send_email:
    path:     /restore/send
    defaults: { _controller: FOSUserBundle:Resetting:sendEmail }

fos_user_resetting_check_email:
    path:     /restore/check
    defaults: { _controller: FOSUserBundle:Resetting:checkEmail }

fos_user_resetting_reset:
    path:     /restore/{token}
    defaults: { _controller: FOSUserBundle:Resetting:reset }

fos_user_profile_show:
    path:     /profile
    defaults: { _controller: AppBundle:Profile:current }

fos_user_security_check:
    path:     /login_check
    defaults: { _controller: FOSUserBundle:Security:check }


registration:
    path:     /registration
    defaults: { _controller: AppBundle:Security:registration }

login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /blog

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

media:
    resource: "@MediaBundle/Controller"
    type:     annotation
    prefix:   /media