# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    web_dir:  '%kernel.project_dir%/web/'
services:
    entry_point.user_login:
        class: AppBundle\LoginEntryPoint
        arguments:
            - '@router'

    app.event_listner.after_registration_listner:
        class: AppBundle\EventListener\AfterRegistrationListner
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }

    app.twig_app_extension:
        class: AppBundle\TwigAppExtension
        tags:
            - { name: twig.extension }

    settings.manager:
        class: AppBundle\SettingManager
        arguments: ['@doctrine.orm.entity_manager', '@app.cache']

    app.team_manager:
        class: AppBundle\TeamManager
        calls:
            - [setContainer, ['@service_container']]
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }