# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    entry_point.user_login:
        class: AppBundle\LoginEntryPoint
        arguments:
            - '@router'